Repository Sparta-bootcamp-master-iOS6IU/kiosk, pull requests merged in 2025-04, with the labels that each got.

#4 ✨ Feat: Segmented Control 구현
  Kiosk/Kiosk/Presentation/Main/MainViewController.swift
  Kiosk/Kiosk/Presentation/MainViewController.swift
  Kiosk/Kiosk/Presentation/Sort/SortSegConstant.swift
  Kiosk/Kiosk/Presentation/Sort/SortSegControl.swift
Labels: enhancement

#6 ✨ Feat: PaymentCell UI 구현
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentConstant.swift
Labels: enhancement

#9 Feature/collection view layout
  Kiosk/Kiosk/Data/Model/Movie.swift
  Kiosk/Kiosk/Presentation/Cart/CartCell.swift
  Kiosk/Kiosk/Presentation/CollectionView/CollectionViewConstant.swift
  Kiosk/Kiosk/Presentation/CollectionView/MovieCollectionView.swift
  Kiosk/Kiosk/Presentation/CollectionView/MovieSectionItem.swift
  Kiosk/Kiosk/Presentation/Common/ReuseIdentifying.swift
  Kiosk/Kiosk/Presentation/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/MainViewController.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
Labels: enhancement

#12 ✨ Feat: 전체삭제 버튼 Event 구현
  Kiosk/Kiosk/Presentation/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentConstant.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentDelegate.swift
  Kiosk/Kiosk/Presentation/Sort/SortSegControl.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: enhancement

#13 ✨ Feat: 결제버튼 Event 구현
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentCellDelegate.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentConstant.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+PaymentCellDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
Labels: enhancement

#18 ✨ Feat: 추가 버튼 탭 이벤트 구현
  Kiosk/Kiosk/Application/DIContainer/AppDIContainer.swift
  Kiosk/Kiosk/Application/DIContainer/UseCaseDIContainer.swift
  Kiosk/Kiosk/Data/UseCase/DefaultTicketRegisterUseCase.swift
  Kiosk/Kiosk/Domain/Error/RegisterTicketError.swift
  Kiosk/Kiosk/Domain/UseCase/TicketRegisterUseCase.swift
  Kiosk/Kiosk/Presentation/Cart/CartConstant.swift
  Kiosk/Kiosk/Presentation/CollectionView/MovieSectionItem.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: enhancement

#19 ✨ Feat: 장바구니 목록 총 금액 표시
  Kiosk/Kiosk/Presentation/CollectionView/MovieSectionItem.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: enhancement

#21 🧑‍💻 Fix: 전체삭제 / 결제 버튼 비활성화
  Kiosk/Kiosk/Presentation/CollectionView/MovieSectionItem.swift
  Kiosk/Kiosk/Presentation/Payment/PaymentCell.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: enhancement

#22 ✨ Feat: 티켓 추가 시 할인 옵션 적용
  Kiosk/Kiosk/Presentation/CollectionView/MovieCollectionView.swift
  Kiosk/Kiosk/Presentation/CollectionView/MovieCollectionViewDelegate.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell+RedCircleOptionButtonDelegate.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/MovieInfo/Subview/RedCircleOptionButton.swift
  Kiosk/Kiosk/Presentation/MovieInfo/Subview/RedCircleOptionButtonDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+MovieCollectionViewDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: enhancement

#23 ✨ Feat: 페이지 컨트롤 업데이트 및 버그 수정
  Kiosk/Kiosk/Presentation/CollectionView/CollectionViewConstant.swift
  Kiosk/Kiosk/Presentation/CollectionView/MovieCollectionView.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell+RedCircleOptionButtonDelegate.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCell.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/MovieInfo/MovieInfoConstant.swift
  Kiosk/Kiosk/Presentation/MovieInfo/Subview/PageControlFooterView.swift
  Kiosk/Kiosk/Presentation/MovieInfo/Subview/RedCircleOptionButton.swift
  Kiosk/Kiosk/Presentation/MovieInfo/Subview/TitleContentView.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+DataSource.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+MovieInfoCellDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController+SortSegControlDelegate.swift
  Kiosk/Kiosk/Presentation/ViewController/MainViewController.swift
  Kiosk/Kiosk/Presentation/ViewModel/CartDelegate.swift
  Kiosk/Kiosk/Presentation/ViewModel/MainViewModel.swift
Labels: bug, enhancement

#26 📝 Docs: Create README.md
  README.md
Labels: documentation
